# Automatically label PRs based on changed files

'tests':
  - changed-files:
    - any-glob-to-any-file: 'tests/**/*'

'documentation':
  - changed-files:
    - any-glob-to-any-file:
      - '**.md'
      - 'docs/**/*'

'dependencies':
  - changed-files:
    - any-glob-to-any-file:
      - 'composer.json'
      - 'composer.lock'

'ci/cd':
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - 'captainhook.json'

'configuration':
  - changed-files:
    - any-glob-to-any-file:
      - '**.xml'
      - '**.neon'
      - '.php-cs-fixer.dist.php'
      - '.editorconfig'

'source':
  - changed-files:
    - any-glob-to-any-file: 'src/**/*'
